### ISSUE TITLE
Feature: Initial creation of Pie chart

### ISSUE THREAD

**Issue by yxin202** [nathanbell806/310A1BudgetTracker#34] opened 2023-08-19 23:12 UTC
**What feature are you asking for**
Insert data into the pie chart.

**Describe the solution you'd like**
Create a pie chart class first. Then create an observable list to store data and create a pie chart with the list.

**Reason**
The user can see their expenses clearer.

**Comment by nbel806** [comment] 2023-08-20 00:06
Is this a duplicate of the budget breakdown view I created?

**Comment by yxin202** [comment] 2023-08-20 00:12
It is more about the logic of the pie chart, not the UI part.

**Closed** 2023-08-20 01:01 UTC
